import os
from dotenv import load_dotenv
import uvicorn
from typing import Optional, Dict, Any
from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, Field

from sandbox.guardrails.sanitizer import CodeSanitizer
from sandbox.agents.graph import secant_graph

load_dotenv()
app = FastAPI(
    title="SecAnt Security Gateway",
    description="Secure Agent Execution Sandbox & Constitutional Evaluation Ingress API",
    version="1.0.0"
)

# Initialize compiled LangGraph flow
compiled_graph = secant_graph()


class GatewayPromptRequest(BaseModel):
    prompt: str = Field(..., description="User prompt or coding task for the multi-agent loop")
    max_retries: Optional[int] = Field(default=3, description="Maximum self-correction loop attempts")


class GatewayExecutionResponse(BaseModel):
    status: str = Field(..., description="Success or Security Block status")
    final_output: str = Field(..., description="Validated and constitutional execution output")
    generated_code: str = Field(..., description="The code generated by the Coder agent")
    is_safe: bool = Field(..., description="Safety status verified by static + LLM guardrails")
    iterations_used: int = Field(..., description="Total correction attempts executed by Coder/Validator")


@app.get("/health", status_code=status.HTTP_200_OK)
def health_check() -> Dict[str, str]:
    """Basic health check endpoint."""
    return {"status": "ok", "service": "SecAnt Gateway"}


@app.post("/api/v1/execute", response_model=GatewayExecutionResponse)
async def execute_agent_pipeline(request: GatewayPromptRequest):
    """
    Ingress endpoint that accepts user task prompts, performs immediate pre-flight
    sanitizing checks, and kicks off the LangGraph multi-agent loop.
    """
    # 1. Pre-flight static inspection on raw prompt
    is_safe_prompt, prompt_violations = CodeSanitizer.inspect_code(request.prompt)
    if not is_safe_prompt:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Prompt blocked by SecAnt Guardrail: {', '.join(prompt_violations)}"
        )

    # 2. Initial state for LangGraph loop
    initial_state = {
        "user_prompt": request.prompt,
        "generated_code": "",
        "execution_result": None,
        "feedback": None,
        "iteration_count": 0,
        "max_retries": request.max_retries,
        "final_output": "",
        "is_safe": True
    }

    try:
        # 3. Execute compiled LangGraph agent loop
        final_state = await compiled_graph.ainvoke(initial_state)

        return GatewayExecutionResponse(
            status="completed" if final_state.get("is_safe") else "security_blocked",
            final_output=final_state.get("final_output", ""),
            generated_code=final_state.get("generated_code", ""),
            is_safe=final_state.get("is_safe", False),
            iterations_used=final_state.get("iteration_count", 0)
        )

    except Exception as exc:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Agent pipeline execution error: {str(exc)}"
        )


if __name__ == "__main__":
    uvicorn.run("gateway:app", host="0.0.0.0", port=8000, reload=True)